[CoreRedirects]

; UE 5.5 redirects.
+FunctionRedirects=(OldName="ActivateCameraRigFunctions.ActivateBaseRig", NewName="ActivatePersistentBaseRig")
+FunctionRedirects=(OldName="ActivateCameraRigFunctions.ActivateGlobalRig", NewName="ActivatePersistentGlobalRig")
+FunctionRedirects=(OldName="ActivateCameraRigFunctions.ActivateVisualRig", NewName="ActivatePersistentVisualRig")

